using System;
using Prince;
using UnityEngine;

public class GameEvents : MonoBehaviour
{
    /// <summary>
    /// Data model for a music event.
    ///
    /// This event are generated by game objects that need to play music al level camera sound controller.
    /// </summary>
    public class MusicEvent : EventArgs
    {
        public string ClipToPlay { get; private set; }

        public MusicEvent(string clip)
        {
            ClipToPlay = clip;
        }
    }

    [Header("WIRING:")] 
    [Tooltip("Needed to register game wide events.")]
    [SerializeField] private EventBus eventBus;
        
    private void Awake()
    {
        eventBus.RegisterEvent<MusicEvent>();
            
    }
}
