name: build_manual

on:
  workflow_call:
    inputs:
      version:
        description: Version for this manual.
        required: true
        type: string
        
  workflow_dispatch: 
    inputs:
      version:
        description: Version for this manual.
        required: true
        type: string


jobs:
  build_manual:
    name: Build usage manual for the game from wiki content.
    runs-on: ubuntu-latest
    env:
      manual_version: ${{ inputs.version }}
    steps:
      - name: Get source code.
        uses: actions/checkout@v3
      
      - name: Install multimarkdown support.
        run: |
          sudo apt update
          sudo apt install cmake build-essential -y
          git clone https://github.com/fletcher/MultiMarkdown-6.git mmd_build
          cd mmd_build
          git submodule init
          git submodule update
          make
          cd build
          sudo make install
          cd ../../
      
      - name: Install Pandoc support.
        run: |
          sudo apt install pandoc -y
          
      - name: Install Latex support.
        run: |
          sudo apt install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra python3-pygments -y
      
      - name: Install Jinja2 support.
        run: |
          sudo apt install python3-jinja2 -y
          
      - name: Clone wiki.
        uses: actions/checkout@v3
        with:
          repository: dante-signal31/Prince_of_Unity.wiki
          path: ./Manual/wiki
      
      - name: Run conversion script.
        working-directory: ./Manual
        run: |
          mkdir output
          mkdir pdf
          ./compile_manual.sh $manual_version

      - name: Upload generated manual.
        uses: actions/upload-artifact@v3
        with:
          name: GameManual
          path: Manual/pdf/PoU_manual.pdf