name: test_and_deploy

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
  
  workflow_dispatch: {}

jobs:  
  tests:
    name: Run unit and functional tests.
    runs-on: ubuntu-latest
    steps:
      - name: Get source code.
        uses: actions/checkout@v3
      
      - name: Cache generated files.
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      - name: Run tests.
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}